### PR TITLE
Add Scrapbook posts to Ship page

### PR DESCRIPTION
**Pull request by lachlanjc**

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝Changed routes:


| [**/ship**](https://v3-git-hc-223-add-scrapbook-posts-to-ship.hackclub.dev/ship) |
|:-:|
|<a href="https://v3-git-hc-223-add-scrapbook-posts-to-ship.hackclub.dev/ship">Screenshot of /ship</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/SKD_mh0343cWfNB0irNuxaTzAGY_.png">(view full size)</a> |







Commit 0da521abed67bb4437ad5e65b38db8f7449961f0 (https://v3-git-hc-223-add-scrapbook-posts-to-ship.hackclub.dev).

**Comment by zanedb** [comment]
this is sooo good

**Comment by aaditgupta21** [comment]
Just wondering, why scrapbook posts and not posts from ship channel

**Comment by lachlanjc** [comment]
1. There's an expectation of privacy in Slack, that your posts are only inside the Slack. When you Scrapbook, you're expecting it to be public
2. Collecting Slack posts & rendering them is actually quite difficult. There are dozens of edge cases, most of which we've already tackled with Scrappy & these components. As such, reusing the infrastructure simplifies this rendering/collecting significantly
3. This page just isn't that important, so this suffices I think

**Pull request merged**
