### PR TITLE
Whitelist channel names

### PR DESCRIPTION
**Pull request by benaubin**
Not tested, but this should whitelist channel names.

### CODE REVIEW

**Comment by lachlanjc** [comment]
Thanks! Could we blacklist a few bad channels instead though? Otherwise it’s going to look like there’s way less activity than there is

**Comment by benaubin** [comment]
@lachlanjc Whitelisted because people are trying to get around.

**Comment by MatthewStanciu** [comment]
@lachlanjc I just talked to Ben about this, and I'm in favor of whitelisting for today and switching to a blacklist tomorrow. I'm going to go ahead and merge, but call me if you want to talk about it

**Comment by lachlanjc** [comment]
Sure, sounds good. Can you just add a bunch more channels?

**Pull request merged**
