### PR TITLE
Fall 2021: Abstract Changes

### PR DESCRIPTION
**Pull request by maxwofford**

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝Changed routes:


| [**/**](https://v3-ac2ma5n1c.hackclub.dev/) |
|:-:|
|<a href="https://v3-ac2ma5n1c.hackclub.dev/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/HLTu78wV1VFIe4XbmnTdQQJWgvSkgHCw6yAYpyE4vjPMH0zN0urMCET_UXgJ-yOO-sHrwHPJMyn71oCeDVwBFw.png">(view full size)</a> |







Commit f23a36e11bd5d4cd165dde9462ea306b1d368a21 (https://v3-ac2ma5n1c.hackclub.dev).

**Comment by ClaireBookworm** [comment]
What if the "Philosophy" banner background was the time lapse?

**Comment by sampoder** [comment]
@ClaireBookworm I think that'd be so great, @leomcelroy @maxwofford thoughts?

**Comment by sampoder** [comment]
Closing for now

**Pull request closed without merging**
