### PR TITLE
Create onboard.js

### PR DESCRIPTION
**Pull request by sahitid**
added an onboard card for the homepage!

### CODE REVIEW

**Comment by radioblahaj** [comment]
let's see how this looks on vercel! authorized a deployment for you :)

**Comment by radioblahaj** [comment]
just to let you know that you forgot to import the comopoent into the main page

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**/**](https://site-lw86rc35k.hackclub.dev/) |
|:-:|
|<a href="https://site-lw86rc35k.hackclub.dev/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/ZTQ1YPboAv1ek5a5uc2t4m7wVM0UsGIh8Krv0nyrjrSiUyyj6yqlnusg7oePEwikqJtk8OL0HGx5Atdhkm13Bg.png">(view full size)</a> |



And 1 other route:
- [**/api/stars**](https://site-lw86rc35k.hackclub.dev/api/stars)



Commit 6eab4bf3b671b56f03dca6b6e9ea1a0c192c17a0 (https://site-lw86rc35k.hackclub.dev).

**Comment by bellesea** [comment]
@sahitid check out the deployment... i think there's a styling error probably w/ the orpheus keychain image. would you like to peer debug this and push the change?

**Comment by malted** [comment]
Any updates?

**Comment by aramshiva** [comment]
I think @developedbytoby made a newer version! #1010. Maybe this should be closed?

**Comment by sampoder** [comment]
I'm going to close this for the time being just so we don't have a massive backlog of PRs. I think this design is really nice so @sahitid if you want to (no obligations) integrate it into the newer one, let me know and I can help :D

**Pull request closed without merging**
