### PR TITLE
bring Santa to the v3!

### PR DESCRIPTION
**Pull request by sampoder**

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝Changed routes:


| [**/santa**](https://v3-8irsxtdvh.hackclub.dev/santa) |
|:-:|
|<a href="https://v3-8irsxtdvh.hackclub.dev/santa">Screenshot of /santa</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/w07BbrWE-PEl4nE6-mx_jo8-tWxtP0UpldlTG6v-0O-jiX4jePN1ouAuO6r_Apc2_ItiS-2KdpbRc5PBaERDZQ.png">(view full size)</a> |







Commit 61936e0f8f54c8c14f9d83d5e1ee196f5db7f174 (https://v3-8irsxtdvh.hackclub.dev).

**Comment by maxwofford** [comment]
Hmmmm, this page has some weird horizontal scrolling going on

**Comment by sampoder** [comment]
yikes I'll fix that

**Comment by sampoder** [comment]
fixed

**Pull request merged**
