### PR TITLE
Improve Slack #counttoamillion badge

### PR DESCRIPTION
**Pull request by lachlanjc**

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝Changed routes:


| [**/slack**](https://v3-git-counttoamillion.hackclub.dev/slack) |
|:-:|
|<a href="https://v3-git-counttoamillion.hackclub.dev/slack">Screenshot of /slack</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/5Qoq8YdJpG6Fbt9whgEfuckz_LY_.png">(view full size)</a> |



And 1 other route:
- [**/api/channels/count-to-a-million**](https://v3-git-counttoamillion.hackclub.dev/api/channels/count-to-a-million)



Commit c68128026fc842f9e662edae2817e1c049023751 (https://v3-git-counttoamillion.hackclub.dev).

**Comment by lachlanjc** [comment]
Check it out @abby9664!! :)

**Comment by abby9664** [comment]
YAY!!!!

**Comment by abby9664** [comment]
Thank you so much :)

**Pull request merged**
